# Generated by Django 5.2.5 on 2025-12-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="image",
            field=models.ImageField(
                default="media/users/image.png", upload_to="users/"
            ),
        ),
    ]
